stages:
  - publish

publish:
  image: node:latest
  stage: publish
  only:
    - main
  script:
    - npm install -g typescript
    - npm install
    - npm run build
    - cp src/server.mjs lib/server.mjs
    - cp -r src/html lib/html
    - npm config set //registry.npmjs.org/:_authToken ${PLAYWRIGHT_HTML_PIPELINE_TOKEN}
    - npm publish
